-- PERSON
CREATE TABLE orf_person (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tenant_id    NUMBER NOT NULL,
    given_name   VARCHAR2(100) NOT NULL,
    family_name  VARCHAR2(100) NOT NULL,
    email        VARCHAR2(256),
    country_code VARCHAR2(2),
    created      TIMESTAMP(6),
    created_by   VARCHAR2(256),
    updated      TIMESTAMP(6),
    updated_by   VARCHAR2(256),
    CONSTRAINT orf_person_pk     PRIMARY KEY (id),
    CONSTRAINT orf_person_fk_tnt FOREIGN KEY (tenant_id) REFERENCES orf_tenant(id),
    CONSTRAINT orf_person_uk_tnt UNIQUE (tenant_id, id)
);
CREATE INDEX orf_person_ix_tnt ON orf_person(tenant_id);
/

-- PROFILE
CREATE TABLE orf_profile (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tenant_id      NUMBER NOT NULL,
    person_id      NUMBER NOT NULL,
    title          VARCHAR2(200),
    summary        CLOB,
    status         VARCHAR2(20),
    published_at   TIMESTAMP(6),
    archived_at    TIMESTAMP(6),
    photo          BLOB,
    photo_mime_type VARCHAR2(100),
    created        TIMESTAMP(6),
    created_by     VARCHAR2(256),
    updated        TIMESTAMP(6),
    updated_by     VARCHAR2(256),
    CONSTRAINT orf_profile_pk        PRIMARY KEY (id),
    CONSTRAINT orf_profile_fk_tnt    FOREIGN KEY (tenant_id) REFERENCES orf_tenant(id),
    CONSTRAINT orf_profile_uk_tnt    UNIQUE (tenant_id, id),
    CONSTRAINT orf_profile_fk_person FOREIGN KEY (tenant_id, person_id)
                                     REFERENCES orf_person(tenant_id, id)
);
CREATE INDEX orf_profile_ix_tnt    ON orf_profile(tenant_id);
CREATE INDEX orf_profile_ix_person ON orf_profile(tenant_id, person_id);
/

-- EXPERIENCE
CREATE TABLE orf_experience (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tenant_id     NUMBER NOT NULL,
    profile_id    NUMBER NOT NULL,
    employer_name VARCHAR2(200),
    job_title     VARCHAR2(200),
    start_date    DATE,
    end_date      DATE,
    description   CLOB,
    created       TIMESTAMP(6),
    created_by    VARCHAR2(256),
    updated       TIMESTAMP(6),
    updated_by    VARCHAR2(256),
    CONSTRAINT orf_experience_pk         PRIMARY KEY (id),
    CONSTRAINT orf_experience_fk_tnt     FOREIGN KEY (tenant_id) REFERENCES orf_tenant(id),
    CONSTRAINT orf_experience_uk_tnt     UNIQUE (tenant_id, id),
    CONSTRAINT orf_experience_fk_profile FOREIGN KEY (tenant_id, profile_id)
                                         REFERENCES orf_profile(tenant_id, id)
);
CREATE INDEX orf_experience_ix_prof ON orf_experience(tenant_id, profile_id);
/

-- EDUCATION
CREATE TABLE orf_education (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tenant_id     NUMBER NOT NULL,
    profile_id    NUMBER NOT NULL,
    institution   VARCHAR2(200),
    program_title VARCHAR2(200),
    eqf_level     VARCHAR2(10),
    start_date    DATE,
    end_date      DATE,
    description   CLOB,
    created       TIMESTAMP(6),
    created_by    VARCHAR2(256),
    updated       TIMESTAMP(6),
    updated_by    VARCHAR2(256),
    CONSTRAINT orf_education_pk         PRIMARY KEY (id),
    CONSTRAINT orf_education_fk_tnt     FOREIGN KEY (tenant_id) REFERENCES orf_tenant(id),
    CONSTRAINT orf_education_uk_tnt     UNIQUE (tenant_id, id),
    CONSTRAINT orf_education_fk_profile FOREIGN KEY (tenant_id, profile_id)
                                        REFERENCES orf_profile(tenant_id, id)
);
CREATE INDEX orf_education_ix_prof ON orf_education(tenant_id, profile_id);
/

-- SKILL
CREATE TABLE orf_skill (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tenant_id  NUMBER NOT NULL,
    label      VARCHAR2(200) NOT NULL,
    esco_uri   VARCHAR2(500),
    category   VARCHAR2(50),
    created    TIMESTAMP(6),
    created_by VARCHAR2(256),
    updated    TIMESTAMP(6),
    updated_by VARCHAR2(256),
    CONSTRAINT orf_skill_pk     PRIMARY KEY (id),
    CONSTRAINT orf_skill_fk_tnt FOREIGN KEY (tenant_id) REFERENCES orf_tenant(id),
    CONSTRAINT orf_skill_uk_tnt UNIQUE (tenant_id, id)
);
CREATE INDEX orf_skill_ix_tnt ON orf_skill(tenant_id);
/

-- PROFILE_SKILL
CREATE TABLE orf_profile_skill (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tenant_id        NUMBER NOT NULL,
    profile_id       NUMBER NOT NULL,
    skill_id         NUMBER NOT NULL,
    proficiency_level VARCHAR2(50),
    evidence         CLOB,
    created          TIMESTAMP(6),
    created_by       VARCHAR2(256),
    updated          TIMESTAMP(6),
    updated_by       VARCHAR2(256),
    CONSTRAINT orf_prof_skill_pk       PRIMARY KEY (id),
    CONSTRAINT orf_prof_skill_fk_tnt   FOREIGN KEY (tenant_id) REFERENCES orf_tenant(id),
    CONSTRAINT orf_prof_skill_fk_prof  FOREIGN KEY (tenant_id, profile_id)
                                       REFERENCES orf_profile(tenant_id, id),
    CONSTRAINT orf_prof_skill_fk_skill FOREIGN KEY (tenant_id, skill_id)
                                       REFERENCES orf_skill(tenant_id, id),
    CONSTRAINT orf_prof_skill_uk       UNIQUE (tenant_id, profile_id, skill_id)
);
CREATE INDEX orf_prof_skill_ix_prof ON orf_profile_skill(tenant_id, profile_id);
/

-- LANGUAGE
CREATE TABLE orf_language (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tenant_id   NUMBER NOT NULL,
    profile_id  NUMBER NOT NULL,
    lang_code   VARCHAR2(10) NOT NULL,
    proficiency VARCHAR2(20),
    is_native   CHAR(1) CHECK (is_native IN ('Y','N')),
    created     TIMESTAMP(6),
    created_by  VARCHAR2(256),
    updated     TIMESTAMP(6),
    updated_by  VARCHAR2(256),
    CONSTRAINT orf_language_pk         PRIMARY KEY (id),
    CONSTRAINT orf_language_fk_tnt     FOREIGN KEY (tenant_id) REFERENCES orf_tenant(id),
    CONSTRAINT orf_language_uk_tnt     UNIQUE (tenant_id, id),
    CONSTRAINT orf_language_fk_profile FOREIGN KEY (tenant_id, profile_id)
                                       REFERENCES orf_profile(tenant_id, id)
);
CREATE INDEX orf_language_ix_prof ON orf_language(tenant_id, profile_id);
/

-- PROFILE_LINK
CREATE TABLE orf_profile_link (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tenant_id  NUMBER NOT NULL,
    profile_id NUMBER NOT NULL,
    label      VARCHAR2(100),
    url        VARCHAR2(1000),
    created    TIMESTAMP(6),
    created_by VARCHAR2(256),
    updated    TIMESTAMP(6),
    updated_by VARCHAR2(256),
    CONSTRAINT orf_profile_link_pk         PRIMARY KEY (id),
    CONSTRAINT orf_profile_link_fk_tnt     FOREIGN KEY (tenant_id) REFERENCES orf_tenant(id),
    CONSTRAINT orf_profile_link_uk_tnt     UNIQUE (tenant_id, id),
    CONSTRAINT orf_profile_link_fk_profile FOREIGN KEY (tenant_id, profile_id)
                                           REFERENCES orf_profile(tenant_id, id)
);
CREATE INDEX orf_profile_link_ix_prof ON orf_profile_link(tenant_id, profile_id);
/

-- PROJECT
CREATE TABLE orf_project (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tenant_id   NUMBER NOT NULL,
    profile_id  NUMBER NOT NULL,
    name        VARCHAR2(200),
    role        VARCHAR2(200),
    start_date  DATE,
    end_date    DATE,
    description CLOB,
    created     TIMESTAMP(6),
    created_by  VARCHAR2(256),
    updated     TIMESTAMP(6),
    updated_by  VARCHAR2(256),
    CONSTRAINT orf_project_pk         PRIMARY KEY (id),
    CONSTRAINT orf_project_fk_tnt     FOREIGN KEY (tenant_id) REFERENCES orf_tenant(id),
    CONSTRAINT orf_project_uk_tnt     UNIQUE (tenant_id, id),
    CONSTRAINT orf_project_fk_profile FOREIGN KEY (tenant_id, profile_id)
                                      REFERENCES orf_profile(tenant_id, id)
);
CREATE INDEX orf_project_ix_prof ON orf_project(tenant_id, profile_id);
/

-- CREDENTIAL
CREATE TABLE orf_credential (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tenant_id   NUMBER NOT NULL,
    profile_id  NUMBER NOT NULL,
    type        VARCHAR2(100),
    title       VARCHAR2(200),
    issuer_name VARCHAR2(200),
    issue_date  DATE,
    expiry_date DATE,
    raw_vc_json CLOB,
    created     TIMESTAMP(6),
    created_by  VARCHAR2(256),
    updated     TIMESTAMP(6),
    updated_by  VARCHAR2(256),
    CONSTRAINT orf_credential_pk         PRIMARY KEY (id),
    CONSTRAINT orf_credential_fk_tnt     FOREIGN KEY (tenant_id) REFERENCES orf_tenant(id),
    CONSTRAINT orf_credential_uk_tnt     UNIQUE (tenant_id, id),
    CONSTRAINT orf_credential_fk_profile FOREIGN KEY (tenant_id, profile_id)
                                         REFERENCES orf_profile(tenant_id, id)
);
CREATE INDEX orf_credential_ix_prof ON orf_credential(tenant_id, profile_id);
/
